apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-rest
  namespace: carhost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-rest
  template:
    metadata:
      labels:
        app: selenium-rest
    spec:
      containers:
        - name: selenium-rest
          image: carhostacr.azurecr.io/selenium-rest:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/session/list
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/session/status
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-rest
  namespace: carhost
spec:
  selector:
    app: selenium-rest
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP